2019-09-11T16:22:25.190088+00:00 app[web.1]: Connection fails: Error: connect ECONNREFUSED 127.0.0.1:3306
2019-09-11T16:22:25.190091+00:00 app[web.1]: It will be retried for the next request.
2019-09-11T16:22:25.191736+00:00 app[web.1]: events.js:186
2019-09-11T16:22:25.191739+00:00 app[web.1]: throw er; // Unhandled 'error' event
2019-09-11T16:22:25.191740+00:00 app[web.1]: ^
2019-09-11T16:22:25.191741+00:00 app[web.1]: 
2019-09-11T16:22:25.191742+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:3306
2019-09-11T16:22:25.191759+00:00 app[web.1]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14)
2019-09-11T16:22:25.191761+00:00 app[web.1]: --------------------
2019-09-11T16:22:25.191768+00:00 app[web.1]: at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2019-09-11T16:22:25.191770+00:00 app[web.1]: at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
2019-09-11T16:22:25.191771+00:00 app[web.1]: at PoolConnection.connect (/app/node_modules/mysql/lib/Connection.js:119:18)
2019-09-11T16:22:25.191773+00:00 app[web.1]: at Pool.getConnection (/app/node_modules/mysql/lib/Pool.js:48:16)
2019-09-11T16:22:25.191774+00:00 app[web.1]: at MySQL.connect (/app/node_modules/loopback-connector-mysql/lib/mysql.js:90:17)
2019-09-11T16:22:25.191782+00:00 app[web.1]: at Object.initializeDataSource [as initialize] (/app/node_modules/loopback-connector-mysql/lib/mysql.js:44:28)
2019-09-11T16:22:25.191783+00:00 app[web.1]: at LocaldbDataSource.DataSource.setup (/app/node_modules/loopback-datasource-juggler/lib/datasource.js:513:19)
2019-09-11T16:22:25.191785+00:00 app[web.1]: at new DataSource (/app/node_modules/loopback-datasource-juggler/lib/datasource.js:145:8)
2019-09-11T16:22:25.191786+00:00 app[web.1]: at new LocaldbDataSource (/app/dist/datasources/localdb.datasource.js:20:9)
2019-09-11T16:22:25.191787+00:00 app[web.1]: at /app/node_modules/@loopback/context/dist/resolver.js:46:16
2019-09-11T16:22:25.191792+00:00 app[web.1]: at Object.transformValueOrPromise (/app/node_modules/@loopback/context/dist/value-promise.js:227:16)
2019-09-11T16:22:25.191794+00:00 app[web.1]: at Object.instantiateClass (/app/node_modules/@loopback/context/dist/resolver.js:41:34)
2019-09-11T16:22:25.191794+00:00 app[web.1]: at /app/node_modules/@loopback/context/dist/binding.js:407:46
2019-09-11T16:22:25.191795+00:00 app[web.1]: at Binding._getValue (/app/node_modules/@loopback/context/dist/binding.js:295:20)
2019-09-11T16:22:25.191796+00:00 app[web.1]: at /app/node_modules/@loopback/context/dist/binding.js:201:29
2019-09-11T16:22:25.191797+00:00 app[web.1]: at /app/node_modules/@loopback/context/dist/resolution-session.js:69:53
2019-09-11T16:22:25.191798+00:00 app[web.1]: Emitted 'error' event on LocaldbDataSource instance at:
2019-09-11T16:22:25.191799+00:00 app[web.1]: at LocaldbDataSource.postInit (/app/node_modules/loopback-datasource-juggler/lib/datasource.js:500:16)
2019-09-11T16:22:25.191800+00:00 app[web.1]: at /app/node_modules/loopback-connector-mysql/lib/mysql.js:102:19
2019-09-11T16:22:25.191801+00:00 app[web.1]: at Handshake.onConnect (/app/node_modules/mysql/lib/Pool.js:58:9)
2019-09-11T16:22:25.191802+00:00 app[web.1]: at Handshake.<anonymous> (/app/node_modules/mysql/lib/Connection.js:525:10)
2019-09-11T16:22:25.191803+00:00 app[web.1]: at Handshake._callback (/app/node_modules/mysql/lib/Connection.js:491:16)
2019-09-11T16:22:25.191804+00:00 app[web.1]: at Handshake.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
2019-09-11T16:22:25.191805+00:00 app[web.1]: at Protocol.handleNetworkError (/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
2019-09-11T16:22:25.191806+00:00 app[web.1]: at PoolConnection.Connection._handleNetworkError (/app/node_modules/mysql/lib/Connection.js:421:18)
2019-09-11T16:22:25.191807+00:00 app[web.1]: at Socket.emit (events.js:209:13)
2019-09-11T16:22:25.191808+00:00 app[web.1]: at emitErrorNT (internal/streams/destroy.js:91:8)
2019-09-11T16:22:25.191809+00:00 app[web.1]: at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2019-09-11T16:22:25.191810+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2019-09-11T16:22:25.191811+00:00 app[web.1]: errno: 'ECONNREFUSED',
2019-09-11T16:22:25.191812+00:00 app[web.1]: code: 'ECONNREFUSED',
2019-09-11T16:22:25.191813+00:00 app[web.1]: syscall: 'connect',
2019-09-11T16:22:25.191814+00:00 app[web.1]: address: '127.0.0.1',
2019-09-11T16:22:25.191815+00:00 app[web.1]: port: 3306,
2019-09-11T16:22:25.191815+00:00 app[web.1]: fatal: true
2019-09-11T16:22:25.191816+00:00 app[web.1]: }
2019-09-11T16:23:09.000000+00:00 app[api]: Build started by user cmshaki@gmail.com
2019-09-11T16:23:53.990105+00:00 app[api]: Deploy 6b943cac by user cmshaki@gmail.com
2019-09-11T16:23:53.990105+00:00 app[api]: Release v74 created by user cmshaki@gmail.com
2019-09-11T16:23:55.831581+00:00 heroku[web.1]: State changed from crashed to starting
2019-09-11T16:23:58.555953+00:00 heroku[web.1]: Starting process with command `npm start`
2019-09-11T16:24:00.423826+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-11T16:24:00.012661+00:00 app[web.1]: 
2019-09-11T16:24:00.012684+00:00 app[web.1]: > newtoni-api@2.4.0 prestart /app
2019-09-11T16:24:00.012686+00:00 app[web.1]: > npm run build
2019-09-11T16:24:00.012687+00:00 app[web.1]: 
2019-09-11T16:24:00.398543+00:00 heroku[web.1]: Process exited with status 1
2019-09-11T16:24:00.283223+00:00 app[web.1]: 
2019-09-11T16:24:00.283242+00:00 app[web.1]: > newtoni-api@2.4.0 build /app
2019-09-11T16:24:00.283243+00:00 app[web.1]: > lb-tsc
2019-09-11T16:24:00.283244+00:00 app[web.1]: 
2019-09-11T16:24:00.290107+00:00 app[web.1]: sh: 1: lb-tsc: not found
2019-09-11T16:24:00.295262+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-09-11T16:24:00.295576+00:00 app[web.1]: npm ERR! syscall spawn
2019-09-11T16:24:00.295831+00:00 app[web.1]: npm ERR! file sh
2019-09-11T16:24:00.296079+00:00 app[web.1]: npm ERR! errno ENOENT
2019-09-11T16:24:00.297497+00:00 app[web.1]: npm ERR! newtoni-api@2.4.0 build: `lb-tsc`
2019-09-11T16:24:00.297670+00:00 app[web.1]: npm ERR! spawn ENOENT
2019-09-11T16:24:00.297882+00:00 app[web.1]: npm ERR!
2019-09-11T16:24:00.298042+00:00 app[web.1]: npm ERR! Failed at the newtoni-api@2.4.0 build script.
2019-09-11T16:24:00.298225+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-11T16:24:00.307927+00:00 app[web.1]: 
2019-09-11T16:24:00.308052+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-11T16:24:00.308121+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-11T16_24_00_299Z-debug.log
2019-09-11T16:24:00.315758+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-09-11T16:24:00.316056+00:00 app[web.1]: npm ERR! errno 1
2019-09-11T16:24:00.317387+00:00 app[web.1]: npm ERR! newtoni-api@2.4.0 prestart: `npm run build`
2019-09-11T16:24:00.317560+00:00 app[web.1]: npm ERR! Exit status 1
2019-09-11T16:24:00.317786+00:00 app[web.1]: npm ERR!
2019-09-11T16:24:00.317925+00:00 app[web.1]: npm ERR! Failed at the newtoni-api@2.4.0 prestart script.
2019-09-11T16:24:00.318056+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-11T16:24:00.328959+00:00 app[web.1]: 
2019-09-11T16:24:00.329146+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-09-11T16:24:00.329255+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-09-11T16_24_00_318Z-debug.log
2019-09-11T16:24:02.000000+00:00 app[api]: Build succeeded
2019-09-11T16:24:13.583167+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=newtoni-api.herokuapp.com request_id=92f6be3a-a771-4839-bad1-054f4886b0ed fwd="196.105.118.16" dyno= connect= service= status=503 bytes= protocol=https
2019-09-11T16:24:19.500851+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/explorer" host=newtoni-api.herokuapp.com request_id=8fd6105f-abc8-4926-b397-96f3b1015a30 fwd="196.105.118.16" dyno= connect= service= status=503 bytes= protocol=https
2019-09-11T16:24:40.734735+00:00 heroku[web.1]: State changed from crashed to down
2019-09-11T16:24:40.336181+00:00 app[api]: Scaled to web@0:Hobby by user cmshaki@gmail.com
2019-09-11T16:25:40.567906+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=newtoni-api.herokuapp.com request_id=58509211-5bce-465f-b38a-2090ae30ade8 fwd="196.105.118.16" dyno= connect= service= status=503 bytes= protocol=https
2019-09-11T16:25:43.400631+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/explorer" host=newtoni-api.herokuapp.com request_id=6afb71d0-ee02-483e-9072-cf1e6a9c9912 fwd="196.105.118.16" dyno= connect= service= status=503 bytes= protocol=https
2019-09-11T16:31:17.000000+00:00 app[api]: Build started by user cmshaki@gmail.com
2019-09-11T16:32:01.026295+00:00 app[api]: Release v75 created by user cmshaki@gmail.com
2019-09-11T16:32:01.026295+00:00 app[api]: Deploy 1f8a85f1 by user cmshaki@gmail.com
2019-09-11T16:32:09.000000+00:00 app[api]: Build succeeded
2019-09-11T16:32:16.279573+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=newtoni-api.herokuapp.com request_id=f0b8ec21-d89e-4355-905d-87cb8fc72476 fwd="196.105.118.16" dyno= connect= service= status=503 bytes= protocol=https
2019-09-11T16:35:43.000000+00:00 app[api]: Build started by user cmshaki@gmail.com
2019-09-11T16:36:26.865710+00:00 app[api]: Deploy a713f824 by user cmshaki@gmail.com
2019-09-11T16:36:26.865710+00:00 app[api]: Release v76 created by user cmshaki@gmail.com
2019-09-11T16:36:37.000000+00:00 app[api]: Build succeeded
2019-09-11T16:37:09.123889+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=newtoni-api.herokuapp.com request_id=e57b20af-5d37-4d80-9fff-f7cbaa16ac2d fwd="196.105.118.16" dyno= connect= service= status=503 bytes= protocol=https
